name: Sync Final Tasks
on:
  push:
    branches: [master]
    paths:
      - 'Module/Module9/Unit6/Module9.Unit6.FinalTask1/**'
      - 'Module/Module9/Unit6/Module9.Unit6.FinalTask2/**'

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync to Target Repo
        run: |
          # Настройка Git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Создаем временную папку
          mkdir -p ../sync-temp
          cd ../sync-temp
          
          # Клонируем целевой репозиторий
          git clone https://${{ github.token }}@github.com/Need4r5peed/Module9.Unit6.FinalTasks.git .
          
          # Полная очистка
          find . -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} +
          
          # Копируем проекты
          mkdir -p Module9.Unit6.FinalTask1 Module9.Unit6.FinalTask2
          cp -r "$GITHUB_WORKSPACE/Module/Module9/Unit6/Module9.Unit6.FinalTask1/"* ./Module9.Unit6.FinalTask1/
          cp -r "$GITHUB_WORKSPACE/Module/Module9/Unit6/Module9.Unit6.FinalTask2/"* ./Module9.Unit6.FinalTask2/

          # Фиксируем изменения
          git add .
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Auto-sync: $(date +'%Y-%m-%d %H:%M:%S')"
            git push origin master
          fi